### ISSUE TITLE
gym version

### ISSUE THREAD

**Issue by YorkNishi999** [falox/gym-adserver#7]
@falox Hello. Thank you for your implementation for this gym environment. It is very valuable for the academic researchers!

I could not use your repo by the most updated gym version (0.26) but after downgrade the gym to 0.18.0, the code worked. So I think the users are happy if we can read the specific version of gym in READ.ME or we can automatically installed the exact version of the gym by setup.py.

Regards,

Yohei

**Comment by falox** [comment]
Thanks @YorkNishi999, I've fixed the code so that you can use 0.26.*. I'm glad this project is useful for research (that was the goal!), feel free to reach out again or open any other PR

**Comment by YorkNishi999** [comment]
@falox  Thank you for your implementation for this repository! I appreciate that.
